services:
  nifi:
    image: apache/nifi:1.21.0
    container_name: nifi
    user: "root"
    ports:
      - "8080:8080"
    networks:
      - confluent
    environment:
      NIFI_WEB_HTTP_PORT: 8080
      NIFI_SECURITY_TRUSTSTORE: "/opt/nifi/nifi-current/cert/truststore.jks"
      NIFI_SECURITY_TRUSTSTORE_TYPE: "JKS"
      NIFI_SECURITY_TRUSTSTORE_PASSWD: "123456"
    volumes:
      - ./nifi_data:/opt/nifi/nifi-current/data
      - ./certs:/opt/nifi/nifi-current/cert
volumes:
  nifi_data:
networks:
  confluent: